version: "2.4"
services:
  weston:
    environment:
    # please uncomment the following line to accept the
    # EULA required to run imx8 vivante graphic drivers
      - ACCEPT_FSL_EULA=1
      - XDG_RUNTIME_DIR=/run/display
    container_name: weston
    image: torizon/arm64v8-debian-weston-vivante:latest
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - "c 4:0 rmw"
      # ... for tty7
      - "c 4:7 rmw"
      # ... for /dev/input devices
      - "c 13:* rmw"
      - "c 199:* rmw"
      # ... for /dev/dri devices
      - "c 226:* rmw"
  totalcross:
    image: totalcross/home-appliance-demo:latest
    command: bash -c "./start.sh"
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
    depends_on:
      - weston
    shm_size: '512mb'
    device_cgroup_rules:
      - 'c 226:* rmw'